### ISSUE TITLE
Willing to become the Official lifter of this package.

### ISSUE THREAD

**Issue by auvipy** [jazzband/python-geojson#129]
I currently get some payment to maintain some open source packages. I would to also maintain this project dedicatedly so that I can claim some more from the sponsors. need non-objection from other maintainers.

cc: @jezdez

**Comment by jezdez** [comment]
Hmm, I'm not sure I or the rest of the Jazzband members can provide a "non-objection" to you receiving payment for maintenance of this or any other Open Source license. If you mean with "lifter" the use of the Tidelift subscription, I'm afraid Jazzband projects are not available for collaboration with Tidelift at this time.

The Jazzband guidelines and code of conduct apply, as well as the [3-clause BSD license](https://github.com/jazzband/python-geojson/blob/master/LICENSE.rst). Take a special look at the third clause, which requires you to ask every contributor to the software for written permission before you use the name of the library or name of contributors for endorsement or promotion of products derived from this software.
