### ISSUE TITLE
Add option to allow specifying floating point precision on geojson.dump/geojson.dumps

### ISSUE THREAD

**Issue by frewsxcv** [jazzband/python-geojson#84]
Just received an email with this request:

> I would like to suggest that you provide a means to specify the 
> precision of floats that the module outputs, perhaps a format string as 
> an argument to dump()/dumps().
> 
> A typical coordinate coming from geojson looks like: [-74.4995503571598, 
> 39.42247551734061]. That's 14 decimal places in the fraction, far, far 
> more than I'll ever need considering that 8 places gives 1.1mm 
> precision. I would like to reduce the file size by limiting the 
> precision to a sensible value.

**Comment by frewsxcv** [comment]
From what I can tell, there's no way to do this via `json.dumps`, so I'm not entirely sure how one would go about this.

**Comment by sgillies** [comment]
@frewsxcv `json.dumps` will not write excess places of precision for rounded floats:

```python
>>> import json
>>> import math
>>> json.dumps(round(math.pi, 2))
'3.14'
```

In my Fiona project, I'm doing this in Cython: https://github.com/Toblerity/Fiona/blob/master/fiona/_transform.pyx#L151-L180. It could be ported?

**Comment by frewsxcv** [comment]
`round` returns a `String`, which might not be what the user wants? I'll think about it.

**Comment by sgillies** [comment]
No, `round()` returns a float. `json.dumps()` returns a string.

**Comment by frewsxcv** [comment]
You're right, not sure what I was thinking. *sips coffee*

That looks like a good solution then.

**Comment by emiliom** [comment]
Has this feature been implemented? I assume not, but checking just in case. Thanks.

**Comment by frewsxcv** [comment]
It hasn't been implemented yet, but if someone had time to implement it, I'd gladly review+merge it

**Comment by dharasty** [comment]
This can be accomplished with the current API via this:

```
def round5(c): return round(c, 5)
rounded_coords_geom = geojson.GeoJSON.to_instance(geojson.utils.map_coords(round5, geometry)

```

**Comment by rayrrr** [comment]
Looking at the [Decimal Degrees](https://en.wikipedia.org/wiki/Decimal_degrees) precision chart, 7 decimal places is the "practical limit of commercial surveying" and 8 is related to "specialized surveying (e.g. tectonic plate mapping)." So, let's go with 8 decimal places as the default; customization can be implemented separately/in parallel.

**Comment by rayrrr** [comment]
I did some more research on the WGS84 Geodetic Datum (the one to which GeoJSON is specifically bound) and it turns out that, according to the [U.S. National Geospatial-Intelligence Agency (PDF link)](http://earth-info.nga.mil/GandG/publications/tr8350.2/tr8350.2-a/Chapter%209.pdf) the accuracy of WGS84 is in the 1 meter range. That puts us in the 5-6 decimal place default range. So we'll go with 6 places instead of 8 as the default.
