### ISSUE TITLE
FeatureCollection validation: FeatureObjects in "features" should contain members

### ISSUE THREAD

**Issue by schaemar** [jazzband/python-geojson#99]
d = {
	"type" : "FeatureCollection",
	"features" : [{}]
}
geojson.is_valid(d)

It's returning "yes" but I would expect:
(source:http://geojsonlint.com/)
Line 3: GeoJSON features must have a type=feature member
Line 3: "properties" member required
Line 3: "geometry" member required

**Comment by rayrrr** [comment]
Hi @schaemar, I am the new maintainer of this repo. I am closing this out because the GeoJSON Format spec actually states that it is possible for a FeatureCollection to be empty ([in section 3.3](https://tools.ietf.org/html/rfc7946#section-3.3)). Thanks!
